require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
install! 'cocoapods', :deterministic_uuids => false

# Explicitly disable Codegen
prepare_react_native_project!

target 'ReactJSMobileApp' do
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
    # Ensure Codegen is skipped
    installer.pods_project.targets.each do |target|
      if target.name == 'React-Codegen'
        target.remove_from_project
      end
    end
  end
end